---
- name: Another network playbook example
  hosts: ~^arista
  gather_facts: no
  task:
  - name: Push to the local system
    copy:
      content: "{{ansible_facts | to_nice_json }}"
      dest: "/home/student/mycode/{{ inventory_hostname }}.txt
